import Head from 'next/head';
import Test from '../components/Test';

export default function Home() {
  fetch('settings', {
    method: 'GET',
  })
    .then((r) => r.json())
    .then((r) => console.log(r));

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Test />
    </div>
  );
}
